# Generated by Django 4.2.2 on 2023-07-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReserveSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='削除されたらTrue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='削除されたらTrue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_number',
            field=models.CharField(default=False, help_text='座席番号', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='削除されたらTrue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_sold_out',
            field=models.BooleanField(default=False, help_text='満席ならTrue'),
            preserve_default=False,
        ),
    ]
