# Generated by Django 4.2.2 on 2023-07-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReserveSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieReserveSystem.seat'),
        ),
    ]
