# Generated by Django 4.2.2 on 2023-07-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReserveSystem', '0002_reservation_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seat_number',
        ),
    ]
