# Generated by Django 4.2.2 on 2023-07-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReserveSystem', '0002_movie_is_deleted_reservation_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='削除されたらTrue'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='削除されたらTrue'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='削除されたらTrue'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_sold_out',
            field=models.BooleanField(default=False, help_text='満席ならTrue'),
        ),
    ]
