# Generated by Django 4.2.2 on 2023-07-24 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReserveSystem', '0003_alter_movie_is_deleted_alter_reservation_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='data_and_time',
            new_name='start_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='作成日'),
        ),
    ]
