# Generated by Django 4.2.2 on 2023-07-24 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReserveSystem', '0004_rename_data_and_time_schedule_start_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ホール名', max_length=128)),
                ('row', models.IntegerField(default=0, help_text='行')),
                ('col', models.IntegerField(default=0, help_text='列')),
            ],
        ),
    ]
