# Generated by Django 4.2.2 on 2023-07-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReserveSystem', '0005_hole'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='hole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MovieReserveSystem.hole'),
            preserve_default=False,
        ),
    ]
