# Generated by Django 4.2.2 on 2023-07-27 14:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReserveSystem', '0009_remove_movie_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row', models.IntegerField(default=0, help_text='行')),
                ('col', models.IntegerField(default=0, help_text='列')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieReserveSystem.hole')),
            ],
        ),
    ]
